out: main.o LinkedList.o
	g++ -o out main.cpp LinkedList.cpp

main.o: main.cpp LinkedList.h 
	g++ -o main.o main.cpp

LinkedList.o: LinkedList.cpp LinkedList.h
	g++ -o LinkedList.o LinkedList.cpp